# Generated by Django 5.1.1 on 2024-10-11 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatistics',
            options={'verbose_name': 'Статистика пользователя', 'verbose_name_plural': 'Статистика пользователей'},
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='answers_given',
            field=models.IntegerField(default=0, verbose_name='Данные ответы'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='donations_made',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Пожертвования'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='questions_asked',
            field=models.IntegerField(default=0, verbose_name='Заданные вопросы'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика вопросов',
                'verbose_name_plural': 'Статистика вопросов',
            },
        ),
        migrations.CreateModel(
            name='AnswerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('answer_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.questionstatistics', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Статистика ответов',
                'verbose_name_plural': 'Статистика ответов',
            },
        ),
        migrations.CreateModel(
            name='ResponseTimeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DurationField(verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.questionstatistics', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Время ответа',
                'verbose_name_plural': 'Время ответов',
            },
        ),
        migrations.CreateModel(
            name='VisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время посещения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика посещений',
                'verbose_name_plural': 'Статистика посещений',
            },
        ),
    ]
