# Generated by Django 5.1.1 on 2024-10-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0002_alter_userstatistics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstatistics',
            name='page_visited',
            field=models.CharField(default='main_page', max_length=100, verbose_name='Страница посещения'),
        ),
    ]
